Added example of Dead Store Elimination
jcrodriguez1989/rco pull request #132
Opened 2019-12-19 08:27 UTC by programming-wizard

2019-12-19 10:31 UTC, ishanrai05 requested changes

2019-12-19 10:31 UTC, ishanrai05 commented on R/opt-dead-store.R
> +#' cat(opt_dead_store(list(verify))$codes[[1]])
it should be `name_len` instead of `verify`.

2019-12-19 11:05 UTC, ishanrai05 approved these changes

2020-07-04 15:23 UTC, jcrodriguez1989 commented
Hi, thanks for your contribution!
Your contribution was included and merged with #168 .

2020-07-04 15:23 UTC, closed without merging